language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: matulef
  password:
    secure: Y5xxVexh+c1Rx33t9zRGk9WK/jLltErZO1nAlCncEOl01guwlHeXH1hgsCgmXgcv6PombXq9rff7ErPcyduPimTSD7ujPkbqt36OnMwG+9sZdQHrfSddrBm9qt7U2lobQ7jSamZYHNDpSpTACDHMVMw0CxCkeK/cx7pD9F+LY76OWnpsojvzLduvSzN9Y7ESrJObhjfdXylnOBD8V9ARAGVGo3AQ/Gi6EuRcGESpY9a3rd42dnKIPIeDGqUN7c6stv2vV1r8JADQPZyais/NhwrZ7ifWwiB+ISTGbyXv2qbfZ+c/D0AccjcvEFcbBk6BsBJlEDb++qqBgn7grkEjWiSglYqnVWXsu35VAZmyyvmovXqPnjXXBN36Tr/ODj4DjUPI1UNI0rdwRXVAC8MNGCvhYN0F+sri48B9ydpqHdQ0TYNOtYJsp6oh+pFmB7G72wejlGEmI2nen1+Jp2c9pJDPdHGmAFW2vu3d7e8OzaaCP4jJ5R4DFjazbfmTi1VjDx1vYJsImWDl1M5om4EMAMuBOt5AIgPb8U20auPgz69j8y8CFul6l1O1IWDGN9YuQMCJ4P7J/97MNKHosYQu8UQ72op1/cLo8UlKA7BGUgvBvLJRkrSKlDmUdqYJLR2Qd0EBAO2fLovq8drnfm8EoYE3cs4j3BrcQ14axyrDBkc=
  on:
    tags: true
    repo: calyxhealth/pyriskadjust
    python: 3.9
