language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: matulef
  password:
    secure: Q6m8+pbw7a+af4jrvA4ajtGT55I2nmJN3iuljTqAaNyE9iQAhlRyKNad0OHExniWNSk5frsktA46vzY/ZzTpvLXyiv6MoNK9aCxq7T4QmHwNJDCjTfyEfrKfzjtMaoVy1xA6uJQm+Sm2bbuRRW+HotJbyftEMaWNgQTb7cLNhu0V3DJlZDYvNyTAsx+HtFcEWBvFFu0cXuh6REDyn9yZrk8RNuWxrVJaOcFIjWyY3wc4fqi3p8KPUUwsT18e7zCY65eoJyHyVWZbqyEpfPXIxAfp8a8kBLvcqAKySVLhs/P6r/C6ed2IUkxCWr5dF6pcqKANWofxOSGB1UP1GowoO8KawRG5g9R8l1X6PpKQAcY+ZuQFEB2WFvylOkjFhUT25+kWy5gmEHRbYGJJoxsTXWHf2O2JuMsP4hQnLR8z1YYB6Drs1fZtIAPzRvDNxfRDWMWofk2mwgxOrprX5ILcUydgDDi2luByS3AZoR/EG4sACilz0j/P4/29qxXjdsdQSYBchfJQBo3zEH/op1GIlAzSINrrtWxfxwBmCkZz7H5L2sIifMCOUP5c1oFKM7NT85cW0bSDFXcHnrTU4RfUx33BI2vWxf5dpffzAKRmXl5IwMYp5yw/4LlH5YFRSXtRWa3rsf4rGZGLaNXv87eUG3pki4U/bymeyEagpZMCefU=
  on:
    tags: true
    repo: calyxhealth/pyriskadjust
    python: 3.9
